### ISSUE TITLE
hyext.request

### ISSUE THREAD

**Issue by clearlove520** [huya-ext/miniapp#7]
报错not in platform

**Comment by dafeizizhu** [comment]
请您在开发工具或者真实直播间调试

https://github.com/huya-ext/miniapp/wiki/Web%E5%BC%80%E5%8F%91%E8%B0%83%E8%AF%95
https://github.com/huya-ext/miniapp/wiki/PC%E5%BC%80%E5%8F%91%E8%B0%83%E8%AF%95
