### ISSUE TITLE
SDK文档示例问题

### ISSUE THREAD

**Issue by Deathencyclopedia** [huya-ext/miniapp#9]
接口:获取当前直播间礼物配置hyExt.context.getGiftConf
[https://github.com/huya-ext/miniapp/wiki/hyExt.context.getGiftConf](url)
示例中为`giftConf.forEach((index, item) `
在测试环境中经测试,在第一个参数中正常获取了礼物数据,而不是示例中的第二个
是否文档有误

**Comment by dafeizizhu** [comment]
文档的问题，感谢提出，已修改
